### ISSUE TITLE
display of clubs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [VillageScribeAssociation/awarenet#327]
```
Firefox 13, Mac, user Lara, mothsorchid


At the Nord-Grundschule, the same club is displayed twice

(Snail society)

http://mothsorchid.com/schools/default/Nord-GrundSchule
```

Original issue reported on code.google.com by `anna.wer...@gmail.com` on 20 Jun 2012 at 7:12

Attachments:
- [Screen shot 2012-06-20 at 9.10.43 .png](https://storage.googleapis.com/google-code-attachments/awarenet/issue-327/comment-0/Screen shot 2012-06-20 at 9.10.43 .png)

**Comment by ooskapenaar** [comment]
This is a dummy comment to demonstrate linking of other issues: #402

**Comment by AMWertlen** [comment]
Strix is going to look at it and fix it.
