### ISSUE TITLE
accidently registered schools

### ISSUE THREAD

**Issue by GoogleCodeExporter** [VillageScribeAssociation/awarenet#378]
```
When registering a new user, one has to choose a school from a drop down. 
Accidently registered schools appear here, too. They are called New School with 
a long random number. They should not appear here.
```

Original issue reported on code.google.com by `a...@villagescribe.org` on 13 Nov 2013 at 11:29

**Comment by AMWertlen** [comment]
Can the "New Schools" please also be deleted from the registration form?
Thank you, Anna

**Comment by awarenetdev** [comment]
Update to fix this should arrive with next batch this weekend.
