### ISSUE TITLE
inbox overload

### ISSUE THREAD

**Issue by AMWertlen** [VillageScribeAssociation/awarenet#405]
I have about 2000 messages in my inbox. Is there a button to mark all and delete them, because they are obviously spam. If not, is there a chance we can have that developed?

**Comment by mrlordsegi** [comment]
Same here

2015-06-10 17:34 GMT+02:00 AMWertlen <notifications@github.com>:

**Comment by LarissaVSA** [comment]
Strix will add a button to delete several messages from the inbox with once click.
