### ISSUE TITLE
multiple upload issue

### ISSUE THREAD

**Issue by lhueneke** [VillageScribeAssociation/awarenet#412]
the uploader stops working after putting the third picture in the queue

**Comment by AMWertlen** [comment]
Please, use the single uploader in the mean time. It can be fixed soon, probably.

**Comment by awarenetdev** [comment]
Fix pushed and deployed to awarenet.eu - all other awarenet instances will need to be updated with this fix.  The change is to package kapenta-live-3 on software updates from http://awarenet.eu/code/.

Closing issue, please reopen if there are further problems.
