### ISSUE TITLE
Changing passwords

### ISSUE THREAD

**Issue by lhueneke** [VillageScribeAssociation/awarenet#413]
As far as we know, the only way to change somebodies password, is to go to his user-edit page. And that seems to only be possible by finding him in the all-users-list. If a few of the learners have forgotten they're passwords, this can take up quite a bit of time. There is a search field to the right, but this only leads you to his profile or his edit-profile page. Is there an easier way to get to the user-edit page or if not, could that be implemented?

**Comment by AMWertlen** [comment]
Yes, there is. 

If you are an administrator, you can access the user-edit page from the profile page by editing the url. 

Examle: http://awarenet.eu/users/edit/profile/ (for your own profile)
http://awarenet.eu/users/edit/L.Hueneke (for somebody else's profile)

**Comment by lhueneke** [comment]
Ah....... right, I remember you actually showed us that in Berlin :)
Thanks
