### ISSUE TITLE
cannot edit basic record

### ISSUE THREAD

**Issue by AMWertlen** [VillageScribeAssociation/awarenet#419]
Hi Strix, I would like to edit the basic record, of eg. http://awarenet.eu/users/edit/profile/M.boko, but I can't open the box. Can you help?

**Comment by awarenetdev** [comment]
Sure, you want either the 'profile' or the 'edit' action, but not both, like so:

http://awarenet.eu/users/edit/M.boko

**Comment by AMWertlen** [comment]
👍  Thanks a lot! :-)
